version: "3.7"

services:

  #  gateway:
  #    image: nginx
  #    volumes:
  #      - ./.docker/config/gateway.conf:/etc/nginx/conf.d/default.conf
  #    depends_on:
  #      - ui
  #      - search-engine
  #      - firebase

  proxy:
    image: snowdreamtech/frpc
    environment:
      - FRP_SERVER_ADDR=${FRP_SERVER_ADDR}
      - FRP_TOKEN=${FRP_TOKEN}
    volumes:
      - ./.docker/frp/frpc.ini:/etc/frp/frpc.ini

    depends_on:
      - ui

  ui:
    image: node:14
    command: yarn workspace @njmaeff/above-and-beyond run dev --hostname=0.0.0.0
    user: node
    working_dir: /workspace
    ports:
      - "9229:9229"
    volumes:
      - ../../:/workspace
      - ./.env.remote:/workspace/src/above-and-beyond/.env

    depends_on:
      - firebase
      - search-engine

  firebase:
    build:
      dockerfile: .docker/firebase.Dockerfile
      context: .
    command: firebase emulators:start --import /home/node/.cache/firebase/data --export-on-exit
    volumes:
      - firebase:/home/node/.cache/firebase

    ports:
      - "9199:9199"
      - "9099:9099"
      - "8080:8080"
      - "8081:8081"
      - "9005:9005"

  search-engine:
    image: typesense/typesense:0.22.0
    command: --data-dir /data --api-key=xyz --enable-cors
    ports:
      - "8108:8108"
    volumes:
      - search-engine:/data
    depends_on:
      - firebase


volumes:
  firebase:
  search-engine:
